# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go.chromium.org/luci/vpython/api/vpython/env.proto
"""Generated protocol buffer code."""
from chromite.third_party.google.protobuf.internal import builder as _builder
from chromite.third_party.google.protobuf import descriptor as _descriptor
from chromite.third_party.google.protobuf import descriptor_pool as _descriptor_pool
from chromite.third_party.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_test.go.chromium.org.luci.vpython.api.vpython import pep425_pb2 as go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_pep425__pb2
from chromite.api.gen_test.go.chromium.org.luci.vpython.api.vpython import spec_pb2 as go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2go.chromium.org/luci/vpython/api/vpython/env.proto\x12\x07vpython\x1a\x35go.chromium.org/luci/vpython/api/vpython/pep425.proto\x1a\x33go.chromium.org/luci/vpython/api/vpython/spec.proto\"u\n\x0b\x45nvironment\x12\x1b\n\x04spec\x18\x01 \x01(\x0b\x32\r.vpython.Spec\x12!\n\x07runtime\x18\x02 \x01(\x0b\x32\x10.vpython.Runtime\x12&\n\npep425_tag\x18\x03 \x03(\x0b\x32\x12.vpython.PEP425Tag\"T\n\x07Runtime\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06prefix\x18\x04 \x01(\t\x12\x0c\n\x04\x61rch\x18\x05 \x01(\tB*Z(go.chromium.org/luci/vpython/api/vpythonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'go.chromium.org.luci.vpython.api.vpython.env_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/luci/vpython/api/vpython'
  _ENVIRONMENT._serialized_start=171
  _ENVIRONMENT._serialized_end=288
  _RUNTIME._serialized_start=290
  _RUNTIME._serialized_end=374
# @@protoc_insertion_point(module_scope)
