# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go.chromium.org/luci/vpython/api/vpython/pep425.proto
"""Generated protocol buffer code."""
from chromite.third_party.google.protobuf.internal import builder as _builder
from chromite.third_party.google.protobuf import descriptor as _descriptor
from chromite.third_party.google.protobuf import descriptor_pool as _descriptor_pool
from chromite.third_party.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5go.chromium.org/luci/vpython/api/vpython/pep425.proto\x12\x07vpython\":\n\tPEP425Tag\x12\x0e\n\x06python\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x62i\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\tB*Z(go.chromium.org/luci/vpython/api/vpythonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'go.chromium.org.luci.vpython.api.vpython.pep425_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(go.chromium.org/luci/vpython/api/vpython'
  _PEP425TAG._serialized_start=66
  _PEP425TAG._serialized_end=124
# @@protoc_insertion_point(module_scope)
