# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/bluetooth_peer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,chromiumos/test/lab/api/bluetooth_peer.proto\x12\x17\x63hromiumos.test.lab.api\"\xba\x02\n\x1d\x42luetoothPeerChameleondConfig\x12\x1e\n\x16next_chameleond_commit\x18\x01 \x01(\t\x12\x16\n\x0enext_dut_hosts\x18\x02 \x03(\t\x12!\n\x19next_dut_release_versions\x18\x03 \x03(\t\x12X\n\x07\x62undles\x18\x04 \x03(\x0b\x32G.chromiumos.test.lab.api.BluetoothPeerChameleondConfig.ChameleondBundle\x1a\x64\n\x10\x43hameleondBundle\x12\x19\n\x11\x63hameleond_commit\x18\x01 \x01(\t\x12\x14\n\x0c\x61rchive_path\x18\x02 \x01(\t\x12\x1f\n\x17min_dut_release_version\x18\x03 \x01(\tB3Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.lab.api.bluetooth_peer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/test/lab/api'
  _BLUETOOTHPEERCHAMELEONDCONFIG._serialized_start=74
  _BLUETOOTHPEERCHAMELEONDCONFIG._serialized_end=388
  _BLUETOOTHPEERCHAMELEONDCONFIG_CHAMELEONDBUNDLE._serialized_start=288
  _BLUETOOTHPEERCHAMELEONDCONFIG_CHAMELEONDBUNDLE._serialized_end=388
# @@protoc_insertion_point(module_scope)
