# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sdk_server.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10sdk_server.proto\"\x0f\n\rUpdateRequest\"1\n\x0eUpdateResponse\x12\x1f\n\x07version\x18\x01 \x01(\x0b\x32\x0e.ChrootVersion\" \n\rChrootVersion\x12\x0f\n\x07version\x18\x01 \x02(\r\"\x0f\n\rStreamRequest\"\x1d\n\x0eStreamResponse\x12\x0b\n\x03num\x18\x01 \x02(\r2@\n\rUpdateService\x12/\n\x0cUpdateChroot\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse2?\n\rStreamService\x12.\n\tGetStream\x12\x0e.StreamRequest\x1a\x0f.StreamResponse0\x01')
)




_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=35,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='UpdateResponse.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=86,
)


_CHROOTVERSION = _descriptor.Descriptor(
  name='ChrootVersion',
  full_name='ChrootVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ChrootVersion.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=120,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=137,
)


_STREAMRESPONSE = _descriptor.Descriptor(
  name='StreamResponse',
  full_name='StreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='StreamResponse.num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=168,
)

_UPDATERESPONSE.fields_by_name['version'].message_type = _CHROOTVERSION
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
DESCRIPTOR.message_types_by_name['ChrootVersion'] = _CHROOTVERSION
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
DESCRIPTOR.message_types_by_name['StreamResponse'] = _STREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREQUEST,
  __module__ = 'sdk_server_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRequest)
  ))
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATERESPONSE,
  __module__ = 'sdk_server_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResponse)
  ))
_sym_db.RegisterMessage(UpdateResponse)

ChrootVersion = _reflection.GeneratedProtocolMessageType('ChrootVersion', (_message.Message,), dict(
  DESCRIPTOR = _CHROOTVERSION,
  __module__ = 'sdk_server_pb2'
  # @@protoc_insertion_point(class_scope:ChrootVersion)
  ))
_sym_db.RegisterMessage(ChrootVersion)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMREQUEST,
  __module__ = 'sdk_server_pb2'
  # @@protoc_insertion_point(class_scope:StreamRequest)
  ))
_sym_db.RegisterMessage(StreamRequest)

StreamResponse = _reflection.GeneratedProtocolMessageType('StreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _STREAMRESPONSE,
  __module__ = 'sdk_server_pb2'
  # @@protoc_insertion_point(class_scope:StreamResponse)
  ))
_sym_db.RegisterMessage(StreamResponse)



_UPDATESERVICE = _descriptor.ServiceDescriptor(
  name='UpdateService',
  full_name='UpdateService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=170,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateChroot',
    full_name='UpdateService.UpdateChroot',
    index=0,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATESERVICE)

DESCRIPTOR.services_by_name['UpdateService'] = _UPDATESERVICE


_STREAMSERVICE = _descriptor.ServiceDescriptor(
  name='StreamService',
  full_name='StreamService',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=236,
  serialized_end=299,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStream',
    full_name='StreamService.GetStream',
    index=0,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_STREAMRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMSERVICE)

DESCRIPTOR.services_by_name['StreamService'] = _STREAMSERVICE

# @@protoc_insertion_point(module_scope)
