# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_test_ready_cli.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-chromiumos/test/api/cros_test_ready_cli.proto\x12\x13\x63hromiumos.test.api\"\x83\x01\n\x13\x43rosTestReadyConfig\x12\x44\n\tchecksums\x18\x01 \x03(\x0b\x32\x31.chromiumos.test.api.CrosTestReadyConfig.KeyValue\x1a&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.cros_test_ready_cli_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _CROSTESTREADYCONFIG._serialized_start=71
  _CROSTESTREADYCONFIG._serialized_end=202
  _CROSTESTREADYCONFIG_KEYVALUE._serialized_start=164
  _CROSTESTREADYCONFIG_KEYVALUE._serialized_end=202
# @@protoc_insertion_point(module_scope)
